### ISSUE TITLE
Coordinate nomenclature is unclear and needs refactoring

### ISSUE THREAD

**Issue by ehthiede** [mjo22/cryojax#91]
Currently, many things are called "coordinates."  

- in VoxelGrid `coordinates` is a plane of frequencies in _Fourier_ space
- in VoxelCloud  `coordinates` (I think?) are an N x 3  of points in _real_ space.  (This matches the use in AtomCloud, but technically there they are different objects, as 
- `coordinates.py` the routine `make_coordinates` returns an (N1 x N2 x N3 x 3) Array giving the real-space positions  (It calls _fftreqs, which also doesn't return fft frequencies if `Real=True`, which is a separate issue.)

I think it would be good to give these different things distinct, descriptive names so it is clear what each one is.

**Possible Solution**
It seems to me that we have 3 formats for storing this sort of data, each of which can be in either Real or Fourier space:
1. A grid of  (N1 x N2 x N3 x 3).  This gives the (x,y,z,) or (k_x, k_y, k_z) value at each grid point in regular 3D grid.
2. A grid of (N1 x N2 x 1 x 3).  This gives the (x,y,z,) or (k_x, k_y, k_z) value at each grid point in a regular 2D grid located on a plane in a 3D space.
3. An array of size (N x 3).  This gives the (x,y,z,) or (k_x, k_y, k_z) value at a bunch of points not located on a regular grid.

We can come up with a name for each, and then prepend "coordinate_" or "frequency_" to make it clear if we are in real or Fourier space.  One option would be.

1. System 
2. Plane
3. List

In this case, a set of all the points in a 3d volume in real space would be a "coordinate_system", in Fourier space it would be a "frequency_system", for the 2D system we would have a "coordinate_plane" or "frequency_plane", etc.

Note: I'm purposefully avoiding "Volume" for number 1 to avoid confusion with the use of the term to refer to the reconstructed electron density.  Also, I'm not sold on having these are the best three words, but they are there to get the juices flowing.

**Comment by mjo22** [comment]
This is a good point. Note that for 2D coordinates, I do make the distinction between real and fourier space: https://github.com/mjo22/cryojax/blob/main/src/cryojax/simulator/manager.py

However, I think there are some deeper issues at play. Staying on the topic of “frequencies” vs “coordinates”, I did not make these names different because I did not want to commit to a particular density representation to being in real vs fourier space until instantiation. If we go down this route, VoxelGrid needs to strictly be a FourierVoxelGrid. Then ElectronDensity.is_real would need to be turned into a ClassVar

Similarly for a coordinate slice vs. coordinate system, for a VoxelGrid it would depend exactly on how this object interacts with the ScatteringModel to know what it should be called (e.g. is the VoxelGrid in real or fourier space? if fourier, are we just using fourier slice or doing something more complicated? etc etc). The hope for the future was that VoxelGrid coordinates could be called one thing, and then a Union type hint could be used to show what it can possibly be.

This gets into an even deeper issue. This points us closer to having a 1-to-1 correspondence between a particular ScatteringModel and a particular ElectronDensity. In general, we probably want to avoid this. But as you say, there should probably be some more balance. There seems to be a bit of a tension between the modularity I imagine when I develop, and the clarity of how things are named.

For now, we should be more concrete though: should we commit to an ElectronDensity class being in real vs fourier space? Or should we commit to ElectronDensity instances being in real vs fourier space?

**Comment by mjo22** [comment]
For nomenclature, I feel similarly that these are good but not sure if they are the best three words. frequency_system is a little confusing to me. What about

1. Grid
2. Slice (to make clear that it is a plane embedded in a volume?)
3. List

Also, what do we think about naming “frequencies” vs “wavevectors”? I’m used to the latter, but I think the best thing to do is to follow conventions in the field. We should also rename 2D coordinates to match new conventions.

**Comment by mjo22** [comment]
Last comment on conventions… I currently have volume coordinates in Angstroms and in-plane coordinates in pixels. I think I did this for good reason, but I don’t fully remember… this is a confusing convention difference though that should also be reevaluated. It is related to this pixel size issue in #88.

**Comment by ehthiede** [comment]
Regarding the names: I like Grid / Slice / List.

Regarding wavevector vs. frequency... I personally find this a bit confusing because wavevector to me always implies specific experimental setups (e.g. diffraction) whereas frequency is just a generic signal processing thing.  But that might be saying something more about my intellectual biases more than anything else.

Regarding the point about whether VoxelGrid, etc should be hardcoded to Fourier / Real space.  I think having separate classes for Real and Fourier space representations makes sense for a few reasons:

1. On some level the code has already made a decision on this: the `from_mrc` routines call explicit routines that return either real or Fourier space results, depending on the class, and the typehints are explicitly Real / Complex.  I think if the user is using real-space routines on an object that has a Fourier space file loader then we are in trouble, even if the resulting code "works".
2. Having explicit classes allows a user to easily tell from the class what they are working with just from its type.
3. We can employ typechecking to ensure real-space densities aren't passed to Fourier-space scattering methods and vice-versa.
4. This is (arguably) better in keeping with the single-responsibility principle.

Following up on the, "will (or should) scattering and volumes be one-to-one?" I think this is something that will come up once we have multislice, etc. implemented, and I think at that point having explicit classes would actually be good: right now since we only have a limited number of scattering routines available it is still possible for the user to keep track of what works with what, but as we get more scattering routines I think it's going to become harder and harder to keep track of.  Either explicit typechecks or even just duck-typing will work much more easily if we have separate classes for different types of densities, as opposed to having one class with many mutually exclusive functionalities.

**Comment by mjo22** [comment]
This makes sense, I agree with this! Let’s go with Grid / Slice / List. What should we call the 2D coordinate systems, stored in the `ImageManager`? These could also be called “Grid” technically, and the fact that they belong to the image configuration could make clear the difference. But, if this is unclear I suppose we could do “Plane”. But then the issue with that is it introduces the dichotomy of something like “volume” vs “plane”, when the naming difference between 3D and 2D is actually “grid” vs “plane”.

See also PR #93. Here, I give the `ScatteringModel` base class the physical 2D coordinate systems as properties. Before, I was computing these on the fly in the `ImagePipeline`. This was a little awkward. I call them `physical_coords`, `physical_freqs`, `physical_padded_coords`, and `physical_padded_freqs`. We should think about the right names for these also. Another candidate is `coords_in_angstroms`, or `coordinate_grid_in_angstroms`. We then will have to make sure we handle this issue I mentioned where the 3D coordinates are stored in Angstroms, while 2D is not. 

In PR #93 I also got started on this issue in my work on the `ElectronDensity`… `ElectronDensity.is_real` is now a `ClassVar`.

Regarding frequency vs wave vector… we should probably stick with frequency. I’m seeing “spatial frequency vector” used in the cryo-EM literature. I’m used to wave vector in physics when describing order parameters, so that’s why I mention…

And regarding correspondences between ScatteringModels and ElectronDensities… I struggle with the right answer to this. I’ve tried to make an initial attempt of a non-1-to-1 correspondence in your first pass of using a non-uniform FFT to get projection images of atoms directly. In general, we want clarity but we also don’t want the package to have too many things for the user to keep track of…

We should also think about this physically—the Ensemble right now has an ElectronDensity (so it is thought of as 3D), but is it more correct to think about an Ensemble as having a ScatteringModel instead (should it really be thought about in 2D)? I like the former, because our goal in cryo is typically to uncover the Ensemble. As you say, we can think more solidly about these details later, when we have things like multislice…

**Comment by mjo22** [comment]
Closing
